conversationAI/models.py
__author__ = 'Mitu'

from datetime import datetime



from conversationAI import db , app



class Comment(db.Model):
    # Setup the relationship to the User table


    # Model for the Blog Posts on Website
    id = db.Column(db.Integer, primary_key=True,autoincrement=True)
    # Notice how we connect the BlogPost to a particular author
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    comment = db.Column(db.Text, nullable=False)

    toxicity = db.Column(db.Text, nullable=False)
    risk = db.Column(db.Text, nullable=False)

    def __unicode__(self):
        return self.id

    def __repr__(self):
        return "Post Id: {} --- Date: {} --- Title: {}".format(self.id,self.date,self.comment)

conversationAI/comment/forms.py
__author__ = 'Mitu'

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField,BooleanField,RadioField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed
from markupsafe import Markup


class CommentPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later

    comment = TextAreaField('Post a Comment', validators=[DataRequired()])

    submit = SubmitField('Post')

conversationAI/__init__.py
__author__ = 'Mitu'


import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate




app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'



basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db = SQLAlchemy(app)
Migrate(app,db)



from conversationAI.comment.views import comment_posts
from conversationAI.core.views import core


# Register the apps
app.register_blueprint(core)
app.register_blueprint(comment_posts)

conversationAI/comment/__init__.py
__author__ = 'Mitu'

conversationAI/comment/views.py
__author__ = 'Mitu'


#blog_comment/views.py

from flask import render_template,url_for,flash, redirect,request,Blueprint,abort
from flask_login import current_user,login_required
from conversationAI import db
from conversationAI.models import Comment
from conversationAI.comment.forms import CommentPostForm
from wtforms.fields import FileField
from perspective import Perspective
from googletrans import Translator
from langdetect import detect


comment_posts = Blueprint('comment_posts',__name__)

allowed = ["TOXICITY",
           "SEVERE_TOXICITY",
           "TOXICITY_FAST",
           "ATTACK_ON_AUTHOR",
           "ATTACK_ON_COMMENTER",
           "INFLAMMATORY",
           "OBSCENE",
           ]

dictionary_toxicity = {"SEVERE_TOXICITY":"Severe toxicity",
           "TOXICITY_FAST" : "Fast toxicity",
           "ATTACK_ON_AUTHOR":"Attack on author",
           "ATTACK_ON_COMMENTER":"Attack on commenter",
           "INFLAMMATORY":"Inflammatory",
           "OBSCENE":"Obscene",
         }
pers = Perspective("AIzaSyDA41FbGVbRgcjnkzx_YjwoDa1qkxRpoA8")
translator = Translator()

@comment_posts.route('/create',methods=['GET','POST'])
def create_post():
    form = CommentPostForm()

    # print("user_id {} \n current_user_id {}".format(blog_posts.user_id,current_user.id))

    if form.validate_on_submit():


        temp_comment = form.comment.data
        if detect(temp_comment) != "en":
            try:
                temp_comment = translator.translate(temp_comment)
                temp_comment = temp_comment.text
            except:
                pass


        analyze_toxicity = pers.score(temp_comment, tests=[allowed[0],allowed[1],allowed[2],allowed[3],allowed[4],allowed[5],
                                                                  allowed[6]

                                                                  ])

        risk = ""
        countindex = 0;
        for key,value in dictionary_toxicity.items():
            countindex += 1;
            if analyze_toxicity[key].score >= 0.3:
                risk += value
                if countindex != 7:
                    risk +=" "



        toxicity = str(analyze_toxicity["TOXICITY"].score)

        comment = Comment(comment = form.comment.data,toxicity = toxicity,risk=risk)
        db.session.add(comment)
        db.session.commit()
        flash(" Comment Created")
        return redirect(url_for('core.index'))

    return render_template('submit.html',form=form)

conversationAI/core/__init__.py
__author__ = 'Mitu'

conversationAI/core/views.py
__author__ = 'Mitu'
from flask import render_template,request,Blueprint
from conversationAI.models import Comment
from conversationAI.comment.forms import CommentPostForm

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''


    page = request.args.get('page', 1, type=int)
    comment = Comment.query.order_by(Comment.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html',comment=comment)



# @core.route('/comment')
# def comment():
#     '''
#     This is the home page view. Notice how it uses pagination to show a limited
#     number of posts by limiting its query size and then calling paginate.
#     '''
#
#     form = CommentPostForm()
#
#     page = request.args.get('page', 1, type=int)
#     comment = Comment.query.order_by(Comment.date.desc()).paginate(page=page, per_page=5)
#     return render_template('submit.html',comment=comment,form=form)

conversationAI/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>


	<meta charset="utf-8">
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BanglaHCI</title>


	<script src="{{ url_for('static', filename='js/jquery.min.js') }}" ></script>

	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"> </script>
	<!--<link  href="static/css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!--&lt;!&ndash; Optional theme &ndash;&gt;-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!--&lt;!&ndash; Latest compiled and minified JavaScript &ndash;&gt;-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<!--&lt;!&ndash;<link rel="stylesheet" href=static/css/style.css">&ndash;&gt;-->

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    {% block head_css %}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">


    {% endblock head_css %}

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- 	<link rel="shortcut icon" href="icon.ico" type="image/x-icon" >
 <!--&ndash;&gt;	<link rel="shortcut icon" href="assets/img/icon.ico">-->

 	<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css') }}">

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}" ></script>





    <!--<script src="{{ url_for('static', filename='ckeditor/ckeditor.js')}}"></script>-->


	

</head>
<body>





<nav class="navbar  navbar-fixed-top" style="background:#D3D3D3; border-bottom:1px solid #ABAEAF;">

	<div class="container-fluid">
		<div class="navbar-header">

			<!-- ham burger-->
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>



		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-left">
				<li > <a style="padding: 30px 10px 30px 10px; color:#495742 ; font-size:1.2em ; font-weight: 600;"  class="nav-link js-scroll-trigger" href="{{ url_for('core.index') }}">HOME</a></li>
                <li><a style="padding: 30px 10px 30px 10px;color:#495742 ; font-size:1.2em ; font-weight: 600; float:right;" class="nav-link js-scroll-trigger" href="{{ url_for('comment_posts.create_post') }}">COMMENT</a></li>



			</ul>

		</div>

	</div>

</nav>



<div class="container">



  {% block content %}

  {% endblock %}
</div>



{% extends "footer.html" %}


  </body>
</html>

conversationAI/templates/footer.html
<footer class="container-fluid text-center" style="background-color:#3C3D41">




	<div class="row" style="margin-top:10px;">
		<div class="col-sm-12 footer_bottom_align" style="background-color:#333331;color:#ffffff">



		</div>

	</div>
</footer>

conversationAI/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="people">
  <div class="container-fluid">

    <div class="col-lg-12 col-md-12">


            <br>


             {% if comment.items|length > 0  %}


            <br>
            <br>

            <div class="row">

                <div class="col-lg-6 col-md-6">


                    <p  class="text-justify nav_item">
                        Comments

                    </p>


                </div>

                <div class="col-lg-3 col-md-3">

                    <p  class="text-justify nav_item">
                        Toxicity Score

                    </p>

                </div>

                <div class="col-lg-3 col-md-3">

                    <p  class="text-justify nav_item">
                        Category

                    </p>

                </div>

            </div>



            {% for post in comment.items %}
             <div class="row">
                <div class="col-lg-6 col-md-6">



                    <p   class="text-justify sub_sub_item">
                        {{post.comment|safe}}

                    </p>






                </div>

                <div class="col-lg-3 col-md-3">


                     {% if (post.toxicity|float) >= 0.2 and (post.toxicity|float) <= 0.4  %}
                    <p style="color:blue;" class="text-justify sub_sub_item">
                        {{post.toxicity|safe}}

                    </p>

                     {% elif (post.toxicity|float) >= 0.5  %}
                    <p  style="color:red;"  class="text-justify sub_sub_item">
                        {{post.toxicity|safe}}

                    </p>

                    {% else %}

                    <p  style="color:green;"  class="text-justify sub_sub_item">
                        {{post.toxicity|safe}}

                    </p>

                    {% endif %}



                </div>

                 <div class="col-lg-3 col-md-3">


                    <p  class="text-justify sub_sub_item">
                        {{post.risk}}

                    </p>


                </div>
             </div>


                <br>

                <div style="height: 1px;max-height: 1%;background-color: #D3D3D3;">

                    </div>
            <br>

            {% endfor %}


            {% else %}


            <div class="col-lg-12 col-md-12">
                <h4 class="nav_item text-center">No Comment Added Yet!</h4>
            </div>

            {% endif %}


    </div>




  </div>

</div>

{% endblock %}

conversationAI/templates/submit.html
{% extends "base.html" %}
{% block content %}
  <div class="people">

      <div class="container-fluid">
            <br>
            <h2 class="nav_item"> </h2>
            <br>
          <div class="col-lg-12 col-md-12">


              <form class="form-group" method="POST" enctype="multipart/form-data">
                 {{ form.hidden_tag() }}



                 <div class="form-group">
                 {{ form.comment.label(class="form-control-label",style="font-size: 1.3em;font-weight: 700; color:#333 bold;") }}
                 {{ form.comment(class="ckeditor form-control-lg")| safe }}
                 </div>



                 <div class="form-group">
                     {{ form.submit(class="btn btn-outline-info") }}
                 </div>
              </form>

            </div>

      </div>

  </div>


{% endblock %}